Heaps of improvements
Make partitions configurable through systemd.repart
Rely on systemd-gpt-auto-generator to mount disks in initrd
Add options to preselect the install device and nixOSConfiguration
Make password hash destination configurable

diff --git a/nix/installer/installer b/nix/installer/installer
--- a/nix/installer/installer
+++ b/nix/installer/installer
@@ -19,25 +19,30 @@ Options:
   --no-sb-check  Don't check if the system is in Setup Mode
   --no-mount     Don't mount the host system flake source if available
   --repourl=URL  Set the installation repository URL [default: \$REPOURL]
+  --install-dev <DEVPATH>  Devicepath to install to
+  --nixosconfig <CONFIG>   Name of nixosConfiguration to install
 "
 # docopt parser below, refresh this parser with `docopt.sh installer`
 # shellcheck disable=2016,2086,2329,1090,1091,2034
 docopt() { local v='2.0.3'; source "${DOCOPT_LIB_SH:?}/docopt-lib.sh" "$v" || {
 ret=$?;printf -- "exit %d\n" "$ret";exit "$ret";};set -e
-trimmed_doc=${DOC:0:487};usage=${DOC:53:32};digest=d7ab3;options=(' --abort-ms'\
+trimmed_doc=${DOC:0:604};usage=${DOC:53:32};digest=a0de3;options=(' --abort-ms'\
 'g 0' ' --auto-reboot 0' ' --no-update 0' ' --no-sb-check 0' ' --no-mount 0' \
-' --repourl 1');node_0(){ switch __abort_msg 0;};node_1(){ switch \
-__auto_reboot 1;};node_2(){ switch __no_update 2;};node_3(){ switch \
-__no_sb_check 3;};node_4(){ switch __no_mount 4;};node_5(){ value __repourl 5;}
-node_6(){ optional 0 1 2 3 4 5;};cat <<<' docopt_exit() { [[ -n $1 ]] && \
-printf "%s\n" "$1" >&2;printf "%s\n" "${DOC:53:32}" >&2;exit 1;}';local \
-varnames=(__abort_msg __auto_reboot __no_update __no_sb_check __no_mount \
-__repourl) varname;for varname in "${varnames[@]}"; do unset "var_$varname";done
-parse 6 "$@";local p=${DOCOPT_PREFIX:-''};for varname in "${varnames[@]}"; do
-unset "$p$varname";done;eval $p'__abort_msg=${var___abort_msg:-false};'$p'__au'\
-'to_reboot=${var___auto_reboot:-false};'$p'__no_update=${var___no_update:-fals'\
-'e};'$p'__no_sb_check=${var___no_sb_check:-false};'$p'__no_mount=${var___no_mo'\
-'unt:-false};'$p'__repourl=${var___repourl:-'"'"'$REPOURL'"'"'};';local \
+' --repourl 1' ' --install-dev 1' ' --nixosconfig 1');node_0(){ switch \
+__abort_msg 0;};node_1(){ switch __auto_reboot 1;};node_2(){ switch \
+__no_update 2;};node_3(){ switch __no_sb_check 3;};node_4(){ switch __no_mount 4
+};node_5(){ value __repourl 5;};node_6(){ value __install_dev 6;};node_7(){
+value __nixosconfig 7;};node_8(){ optional 0 1 2 3 4 5 6 7;};cat <<<' \
+docopt_exit() { [[ -n $1 ]] && printf "%s\n" "$1" >&2;printf "%s\n" \
+"${DOC:53:32}" >&2;exit 1;}';local varnames=(__abort_msg __auto_reboot \
+__no_update __no_sb_check __no_mount __repourl __install_dev __nixosconfig) \
+varname;for varname in "${varnames[@]}"; do unset "var_$varname";done;parse 8 \
+"$@";local p=${DOCOPT_PREFIX:-''};for varname in "${varnames[@]}"; do unset \
+"$p$varname";done;eval $p'__abort_msg=${var___abort_msg:-false};'$p'__auto_reb'\
+'oot=${var___auto_reboot:-false};'$p'__no_update=${var___no_update:-false};'\
+$p'__no_sb_check=${var___no_sb_check:-false};'$p'__no_mount=${var___no_mount:-'\
+'false};'$p'__repourl=${var___repourl:-'"'"'$REPOURL'"'"'};'$p'__install_dev=$'\
+'{var___install_dev:-};'$p'__nixosconfig=${var___nixosconfig:-};';local \
 docopt_i=1;[[ $BASH_VERSION =~ ^4.3 ]] && docopt_i=2;for \
 ((;docopt_i>0;docopt_i--)); do for varname in "${varnames[@]}"; do declare -p \
 "$p$varname";done;done;}
@@ -68,7 +73,7 @@ docopt_i=1;[[ $BASH_VERSION =~ ^4.3 ]] && docopt_i=2;for \
   fi
 
   if ! curl -skf --connect-timeout 1 https://cache.nixos.org >/dev/null; then
-    printf "Waiting for an internet connection...\n" >&2
+    info "Waiting for an internet connection..."
     local timeout=10
     while true; do
       sleep 1
@@ -99,37 +104,32 @@ docopt_i=1;[[ $BASH_VERSION =~ ^4.3 ]] && docopt_i=2;for \
   info "Cleaning leftovers from previous install attempt"
   ! findmnt /mnt/boot >/dev/null || umount /mnt/boot
   if findmnt /mnt >/dev/null; then
-    rm -rf /mnt/etc/nixos
     umount /mnt
   fi
   [[ ! -b /dev/mapper/nixos ]] || cryptsetup close nixos
 
-# boot.lanzaboote.enable
   # Make sure we can enroll the secure boot keys
   # shellcheck disable=SC2154
   $__no_sb_check || sbctl status --json | jq -e .setup_mode >/dev/null 2>&1 || \
     fatal "Your system is not in Setup Mode! Reset secure boot keys so they can be enrolled. You can disable this check with '--no-sb-check'"
 
-  local disk hostname bootsize username_pwdest pwdest password
-  disk=$(get_installdev)
-  hostname=$(get_hostname)
-  bootsize=$(get_bootsize)
-  encrootlabel=$(get_config "$hostname" 'fileSystems."/".encrypted.blkDev' | jq -re)
-  [[ $encrootlabel = /dev/disk/by-label/* ]] || fatal "The configuration for \"%s\" does not have full disk encryption enabled, unable to continue" "$hostname"
-  encrootlabel=${encrootlabel#"/dev/disk/by-label/"}
-  rootformat=$(get_config "$hostname" 'fileSystems."/".fsType' | jq -re)
-  rootmountopts=$(get_config "$hostname" 'fileSystems."/".options' | jq -re '. | join(",")')
-  recoverykeypath=$(get_config "$hostname" 'sbfde.full-disk-encryption.recoveryKeyPath' | jq -re)
-  enrollemptykey=$(get_config "$hostname" 'sbfde.full-disk-encryption.enrollEmptyKey' | jq -r)
-  enrollfallbackpassword=$(get_config "$hostname" 'sbfde.full-disk-encryption.enrollFallbackPassword' | jq -r)
-  rootlabel=$(get_config "$hostname" 'fileSystems."/".encrypted.label' | jq -re)
-  allowdiscards=$(get_config "$hostname" "boot.initrd.luks.devices.$rootlabel.allowDiscards" | jq -r)
-
-  if username_pwdest=$(get_config "$hostname" users.users | \
-    jq -re '[.[] | select(.hashedPasswordFile != null and .enable)] | first | (.name, .hashedPasswordFile)'); then
-    pwdest=${username_pwdest#*$'\n'}
-    password=$(get_secret $INSTALLTMP/user_password "Enter a password for \"${username_pwdest%$'\n'*}\"")
+  local installdev nixosconfig pwdest
+  if [[ -n $__install_dev ]]; then
+    installdev=$__install_dev
+  else
+    installdev=$(get_installdev)
   fi
+  if [[ -n $__nixosconfig ]]; then
+    nixosconfig=$__nixosconfig
+  else
+    nixosconfig=$(get_nixosconfig)
+  fi
+  recoverykeypath=$(get_config "$nixosconfig" sbfde.recoveryKeyPath | jq -re)
+  enrollemptykey=$(get_config "$nixosconfig" sbfde.enrollEmptyKey | jq -r)
+  enrollfallbackpassword=$(get_config "$nixosconfig" sbfde.enrollFallbackPassword | jq -r)
+  repartdefinitions=$(nix build "$REPOURL#nixosConfigurations.\"$nixosconfig\".config.sbfde.repartDefinitions" --print-out-paths)
+  ! pwdest=$(get_config "$nixosconfig" sbfde.hashedPasswordFile | jq -re) || \
+    get_secret $INSTALLTMP/user_password "Enter your user password"
 
   if $enrollfallbackpassword; then
     # Prompt, then prepare enrollment of a fallback FDE password
@@ -141,24 +141,12 @@ docopt_i=1;[[ $BASH_VERSION =~ ^4.3 ]] && docopt_i=2;for \
 
   clear
 
-  # Setup GPT table, then format disk with repart
   info "Formatting disk"
-  parted "$disk" -- mklabel gpt
-  mkdir -p $INSTALLTMP/repart.d
-  local file
-  for file in "${REPART_D:?}"/*; do
-    # shellcheck disable=SC2094
-    BOOTSIZE=$bootsize \
-    ROOTLABEL=$encrootlabel \
-    ROOTFORMAT=$rootformat \
-      envsubst "\${BOOTSIZE} \${ROOTLABEL} \${ROOTFORMAT}" <"$file" >$INSTALLTMP/repart.d/"$(basename "$file")"
-  done
-
   mkdir -p "$(dirname $INSTALLTMP/empty.key)"
   (umask 0066; touch $INSTALLTMP/empty.key)
-  systemd-repart --dry-run=no \
+  systemd-repart --dry-run=no --empty=force \
     --key-file $INSTALLTMP/empty.key \
-    --definitions $INSTALLTMP/repart.d "$disk"
+    --definitions "$repartdefinitions" "$installdev"
 
   # When systemd-repart returns the device nodes for the partitions might not exist yet.
   # Give udev a second or two.
@@ -166,19 +154,15 @@ docopt_i=1;[[ $BASH_VERSION =~ ^4.3 ]] && docopt_i=2;for \
 
   # Properly discover devpaths of the partitions, slapping on a "1" and "2" won't work for e.g. /dev/nvme0n1p2
   local esp_devpath root_devpath
-  esp_devpath=$(lsblk -JO "$disk" | jq -r '.blockdevices[].children[] | select(.partn==1) | .path')
-  root_devpath=$(lsblk -JO "$disk" | jq -r '.blockdevices[].children[] | select(.partn==2) | .path')
+  esp_devpath=$(lsblk -JO "$installdev" | jq -r '.blockdevices[].children[] | select(.partn==1) | .path')
+  root_devpath=$(lsblk -JO "$installdev" | jq -r '.blockdevices[].children[] | select(.partn==2) | .path')
 
   # Attach the encrypted disk using the empty password
   info "Attaching encrypted disk"
-  if $allowdiscards; then
-    cryptsetup open --allow-discards --key-file=$INSTALLTMP/empty.key "$root_devpath" nixos
-  else
-    cryptsetup open --key-file=$INSTALLTMP/empty.key "$root_devpath" nixos
-  fi
+  cryptsetup open --key-file=$INSTALLTMP/empty.key "$root_devpath" nixos
 
   info "Mounting root & boot"
-  mount -o "$rootmountopts" /dev/mapper/nixos /mnt
+  mount /dev/mapper/nixos /mnt
   (umask 0066; mkdir /mnt/boot)
   mount "$esp_devpath" /mnt/boot
 
@@ -202,13 +186,13 @@ docopt_i=1;[[ $BASH_VERSION =~ ^4.3 ]] && docopt_i=2;for \
   fi
 
   info "Installing NixOS"
-  nixos-install --verbose --no-root-password --root /mnt --flake "$REPOURL#$hostname"
+  nixos-install --verbose --no-root-password --root /mnt --flake "$REPOURL#$nixosconfig"
 
-  if [[ -n $password ]]; then
+  if [[ -n $pwdest ]]; then
     info "Copying hashed user password to the system"
     mkdir -p "$(dirname "/mnt$pwdest")"
     chmod 755 "$(dirname "/mnt$pwdest")"
-    printf "%s" "$password" | mkpasswd --stdin >"/mnt$pwdest"
+    cat $INSTALLTMP/user_password | mkpasswd --stdin >"/mnt$pwdest"
     chmod 600 "/mnt$pwdest"
   fi
 
@@ -238,7 +222,7 @@ docopt_i=1;[[ $BASH_VERSION =~ ^4.3 ]] && docopt_i=2;for \
 }
 
 get_installdev() {
-  local dev text dialog_args=() devices=()
+  local dev installdev text dialog_args=() devices=()
   while read -r -d $'\n' dev text; do
     devices+=("$dev")
     dialog_args+=("$dev" "$text")
@@ -247,35 +231,28 @@ get_installdev() {
       .type != "loop" and
       .fstype != "iso9660"
     ) | "\(.path) \([(.children // [])[] | .label | select(. != "ESP" and . != null)] | first // "unlabeled"), \(.serial // "No serial") (\(.model // "Unknown model"), \(.size))"')
-  if [[ ${#devices[@]} -eq 0 ]]; then
-    printf "Did not find any disk installation candidates, run \`installer <DEVPATH>\`\n"  >&2
-    return 1
-  fi
-  dialog --stdout --menu "Select the disk where NixOS should be installed" 15 80 10 "${dialog_args[@]}"
-}
-
-get_hostname() {
-  local confignames configname dialog_args=()
-  confignames=$(nix flake show --json "$REPOURL" | jq -r '.nixosConfigurations | keys[]')
-  while IFS= read -r -d $'\n' configname; do
-    dialog_args+=("$configname" "$configname")
-  done <<<"$confignames"
-  dialog --stdout --menu "Select the NixOS configuration you would like to install" 15 80 10 "${dialog_args[@]}"
-}
-
-get_bootsize() {
-  local bootsize prev_bootsize=1G
-  [[ ! -e $INSTALLTMP/bootsize ]] || prev_bootsize=$(cat $INSTALLTMP/bootsize)
+  [[ ${#devices[@]} -gt 0 ]] || fatal "No disk installation candidates found. Run \`install-nixos --install-dev <DEVPATH>\`"
   while true; do
-    bootsize=$(dialog --stdout --inputbox $'Specify the size of /boot\n(use M or G suffix)' 7 45 "$prev_bootsize")
-    if [[ ! $bootsize =~ ^[0-9]+[MG]$ ]]; then
-      dialog --stdout --msgbox "Invalid size specified!" 7 45
-    else
-      break
+    installdev=$(dialog --stdout --menu "Select the disk where NixOS should be installed" 15 80 10 "${dialog_args[@]}")
+    [[ -n $installdev ]] || return 1
+    if [[ -n $(lsblk -noFSTYPE,PTTYPE "$installdev") ]]; then
+      dialog --stdout --yesno "The disk '$installdev' is not empty."$'\nAre you sure you want to wipe all data on it?' 15 80 || \
+        continue
     fi
+    break
   done
-  printf "%s" "$bootsize" >$INSTALLTMP/bootsize
-  printf "%s" "$bootsize"
+  printf "%s\n" "$installdev"
+}
+
+get_nixosconfig() {
+  local nixosconfigs nixosconfig dialog_args=()
+  nixosconfigs=$(nix flake show --json "$REPOURL" | jq -r '.nixosConfigurations | keys[]')
+  while IFS= read -r -d $'\n' nixosconfig; do
+    ! get_config "$nixosconfig" sbfde.includeInSelection 2>/dev/null | jq -re >/dev/null || \
+      dialog_args+=("$nixosconfig" "$nixosconfig")
+  done <<<"$nixosconfigs"
+  [[ ${#dialog_args[@]} -gt 0 ]] || fatal "No usable nixosConfigurations found."
+  dialog --stdout --menu "Select the NixOS configuration you would like to install" 15 80 10 "${dialog_args[@]}"
 }
 
 get_secret() {
@@ -295,13 +272,12 @@ get_secret() {
     fi
   done
   printf "%s" "$password" >"$save_path"
-  printf "%s" "$password"
 }
 
 get_config() {
-  local hostname=$1 configpath=$2
-  nix eval --json "$REPOURL#nixosConfigurations.\"$hostname\".config.$configpath" || \
-    fatal "Unable to retrieve configpath %s for host %s" "$configpath" "$hostname"
+  local nixosconfig=$1 configpath=$2
+  nix eval --json "$REPOURL#nixosConfigurations.\"$nixosconfig\".config.$configpath" || \
+    fatal "Unable to retrieve configpath %s for host %s" "$configpath" "$nixosconfig"
 }
 
 timeout_msg() {
